const enRegister = {
    title: 'Register Form',
    name: 'Name',
    name_required: 'Name is required',
    name_min: 'Minimum length is 3',
    name_max: 'Maximum length is 15',
    phone: 'Phone',
    phone_required: 'Phone is required',
    invalid_phone: 'Enter a valid phone number',
    email: 'Email',
    email_required: 'Email is required',
    invalid_email: 'Enter a valid email',
    password: 'Password',
    repass: 'Repassword',
    password_required: 'Password is required',
    invalid_password: 'Enter a valid password',
    confirm_password: 'Confirm Password',
    confirm_password_required: 'Confirm Password is required',
    not_matched: 'Passwords do not match',
    register_button: 'Register',
    have_account: "I have an account ",
    login_page: 'Login',
};

export default enRegister;
